### ISSUE TITLE
Error on adding this cartridge

### ISSUE THREAD

**Issue by ghost** [boekkooi/openshift-cartridge-nginx#12]
Hello, I'm trying install this cartridge but I'm having this error when creating application.
The cartridge manifest at 'https://github.com/boekkooi/openshift-cartridge-nginx' could not be downloaded: The cartridge manifest at 'https://github.com/boekkooi/openshift-cartridge-nginx' must be smaller than 20480 bytes.

What should I do?

**Comment by boekkooi** [comment]
Hi @fehmathais,

It looks like you are using the wrong url to get the manifest try http://cartreflect-claytondev.rhcloud.com/github/boekkooi/openshift-cartridge-nginx

**Comment by ghost** [comment]
Hi @boekkooi, I'm sorry and thank you!
