### ISSUE TITLE
Navigation to subdirectories does not happen

### ISSUE THREAD

**Issue by arnabdas** [boekkooi/openshift-cartridge-nginx#13]
Hi,

We have created one app: http://site-dreammaker.rhcloud.com/blog, in Openshift, using this cartridge configuration. But whenever I'm trying to go any sub-directory (eg. http://site-dreammaker.rhcloud.com/blog), Openshift redirects towards port url: http://site-dreammaker.rhcloud.com:8080/blog/. Though the sub-directory contains an `index.html` file.

Please help me, to overcome this issue.

Thanks & regards,
Arnab

**Comment by boekkooi** [comment]
Hi @arnabdas,

Could you please provide the `.openshift/nginx.conf.erb` that you use in your repository?

If you do not have this file yet you can use [conf/nginx_http.conf.erb](https://github.com/boekkooi/openshift-cartridge-nginx/blob/master/conf/nginx_http.conf.erb) as the starting point.
