### ISSUE TITLE
No config files 

### ISSUE THREAD

**Issue by zubair-xda** [boekkooi/openshift-cartridge-nginx#16]
I am unable to find config files of nginx nor nginx folder anywhere. Everything worked great successfully installed added your php cartirade added mysql from openshift but when adding 
# pass the PHP scripts to PHP-FPM

location ~ .php$ {
    fastcgi_pass unix:<%= ENV['OPENSHIFT_PHP_SOCKET'] %>;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    fastcgi_param PATH_INFO $fastcgi_script_name;
    include <%= ENV['OPENSHIFT_NGINX_DIR'] %>/usr/nginx-<%= ENV['OPENSHIFT_NGINX_VERSION'] %>/conf/fastcgi_params;
}
I am unable to find config file to add this.

**Comment by boekkooi** [comment]
Hi @zubair-xda,

Please see [the docs in the readme for php](https://github.com/boekkooi/openshift-cartridge-php#configuration) this references the `nginx.conf.erb` which you will need to create the default template for this is located [here](https://github.com/boekkooi/openshift-cartridge-nginx/blob/master/template/.openshift/nginx.conf.erb).

Good luck!

**Comment by zubair-xda** [comment]
Thanks it solved :)
