### ISSUE TITLE
Not able to scale gears.

### ISSUE THREAD

**Issue by weplan9** [boekkooi/openshift-cartridge-nginx#2]
I have created my application with the following command:

rhc create-app myapp --env OPENSHIFT_NGINX_VERSION=1.7.10 http://cartreflect-claytondev.rhcloud.com/github/boekkooi/openshift-cartridge-nginx -s --env OPENSHIFT_PHP_VERSION=5.5.22 http://cartreflect-claytondev.rhcloud.com/github/boekkooi/openshift-cartridge-php

Application gets created with two cartridges: 1) Nginx and 2) Php

But as soon as I want to scale my app, It throws an error:

Activation of new gears failed: 558335955973ca62cf00003c: Error activating gear: CLIENT_ERROR: Failed to execute: 'control start' for /var/lib/openshift/558335955973ca62cf00003c/php

[18-Jun-2015 17:18:47] NOTICE: [pool www] 'user' directive is ignored when FPM is not running as root

[18-Jun-2015 17:18:47] NOTICE: [pool www] 'group' directive is ignored when FPM is not running as root

[18-Jun-2015 17:18:47] ERROR: An another FPM instance seems to already listen on /var/lib/openshift/558335955973ca62cf00003c/php//run/php.socket

[18-Jun-2015 17:18:47] ERROR: FPM initialization failed

PHP enviroment successfully installed.
Version: 5.5.22
Unable to complete the requested operation due to: An invalid exit code (1) was returned from the server euw-csm-node2.prod.rhcloud.com.  This indicates an unexpected problem during the execution of your request.
    Reference ID: 600b4751f4988f59a026243685c06e16

![scale-fail](https://cloud.githubusercontent.com/assets/10498028/8242798/793a016e-162b-11e5-80f6-66cffe95c17f.png)

Any thoughts why this is happening?

**Comment by robertquest** [comment]
Yes I have this problem too,  this is the bug, but You can see this demo tutorials, soon will be avalible
https://www.youtube.com/watch?v=KMSl0wqawc0

**Comment by boekkooi** [comment]
@weplan9 Thanks for reporting your issue. 

It seems that the socket file is already being used by 1 nginx instance while the new one also tries to use it. A way to fix this would be to change `OPENSHIFT_PHP_SOCKET` to be a IP address + port. 
This would also mean that you would need to edit `.openshift/nginx.conf.erb` to remove `unix:`.

Another possible fix is to create your app as followed.

``` BASH
rhc create-app myapp http://cartreflect-claytondev.rhcloud.com/github/boekkooi/openshift-cartridge-nginx
rhc cartridge add -a myapp http://cartreflect-claytondev.rhcloud.com/github/boekkooi/openshift-cartridge-php
```

(I will try to take a look at the problem this weekend and I will try to fix it.)

@robertquest Since it seems you have experience with this bug can you maybe explain a bit better what is happening according to you?

**Comment by weplan9** [comment]
Hello Boekkooi,

I have tried creating my app with your suggested method:

```
rhc create-app myapp http://cartreflect-claytondev.rhcloud.com/github/boekkooi/openshift-cartridge-nginx
rhc cartridge add -a myapp http://cartreflect-claytondev.rhcloud.com/github/boekkooi/openshift-cartridge-php
```

But it didn't worked, When i want to scale the same error.

Then i wanted to try your other suggestion that I should remove the `unix:` and should try it with an IP and port instead.

I created a new app, went to `.openshift/nginx.conf.erb` and found out that there is no configuration for php FPM yet. I had to add it after the app is created.

So I think its not an issue of `unix` socket, Because the settings is not there.

But i will still try with IP address. Will report back.

**Comment by boekkooi** [comment]
@weplan9 Thanks for testing. The problem was in the PHP cartridge. It has been fixed now so please remove the PHP cartridge and install it again.

```
rhc cartridge remove -a myapp --confirm  php
rhc cartridge add -a myapp http://cartreflect-claytondev.rhcloud.com/github/<user>/openshift-cartridge-php
```

**Comment by boekkooi** [comment]
P.S. Thanks again for reporting the issue and if you have any problems please let me know

**Comment by weplan9** [comment]
Thanks for the Fix, It's working perfect now. Tested with nginx 1.7.10 and PHP 5.6.6
