### ISSUE TITLE
Dynamic scaled gears php-fpm issue.

### ISSUE THREAD

**Issue by weplan9** [boekkooi/openshift-cartridge-nginx#4]
I am facing another strange issue.

Seems like `php-fpm` is not picking up changes from:
`.openshift\fpm\php-fpm.conf.erb`

But only for the dynamically created gears. For local gear its working fine.
New dynamic gear starts with default setting of `php-fpm` which is:

`pm.max_children = 5`

But I had it set `pm.max_children = 15`.

To fix this I have to SSH into that specific gear. Restart that dynamic gear with `ctl_all restart`

As soon as gear restarts it picks up the my new setting defined in:
`.openshift\fpm\php-fpm.conf.erb`

I have tried it both `build` and `deploy` files in `.openshift\action_hooks`
With the following contents:

```
#!/bin/bash
set -e

# Build PHP extra's
# Update conf/ini filesand install pecl extensions

echo Building PHP Extra
${OPENSHIFT_PHP_DIR}/bin/control build
```

Hope i am able to explain the issue I am facing.

Thanks for setting up this cartridge, Its so easy to work with.

**Comment by weplan9** [comment]
I got it fixed by uploading the files to my github repo.

Seems like when the dynamic gear (other than local gears) first starts it picks up the files from github repo.

Dynamic gears should pick the settings from the local synced git repo, Not the github ones.

Suppose If i have 3 projects on openshift, I have to create and maintain 3 different github repo. Each one for different projects.

**Comment by boekkooi** [comment]
Hey @weplan9, 

Let me check that I understand the issue correctly. After you created a app using the nginx and php cartridge. 
Then you change the `.openshift\fpm\php-fpm.conf.erb` in your project repo and push it to openshift.

When you then scale up the app the new cartridge won't use the repo's `.openshift\fpm\php-fpm.conf.erb` but it uses the default [`php-fpm.conf.erb`](https://github.com/boekkooi/openshift-cartridge-php/blob/master/conf/php-fpm.conf.erb).
Is this the issue?

**Comment by weplan9** [comment]
Exactly, This is the issue but with one exception.

When we scale an app, There is a local gear and then it creates new dynamic gears.

That local gear picks up the settings from `.openshift\fpm\php-fpm.conf.erb' that's fine.

But with a brand new dynamic gear it picks up the settings from default github repo.
In my case i am using mine github URL forked from this.

So to fix the issue temporary i have updated my github's `.openshift\fpm\php-fpm.conf.erb`
But if i have multiple application I will have to create new github repos for every openshift project.

It's only notice able if you SSH into that dynamic gear. To do that i use the following command:
`rhc app show --gears` Then i am able to ssh into the gear and can see it has picked up the default settings i have used. Not the current local gear settings. If i restart the dynamic gear using SSH `ctl_all restart` It also fix the issue. But you know we cannot do that for every dynamic gear.

Previously i have been using the following github repo, It not updated anymore that's why i am not using it anymore but I didn't faced this issue on the following repo. Maybe this can help.
It's a single Cartridge for both nginx and php-fpm

https://github.com/getupcloud/openshift-nginx-php-fpm

**Comment by boekkooi** [comment]
So after a lot of trying and failing it seems that there is no way for a plugin to be scaled and have a trigger after the repo is mounted. This causes the problem.

I have added a fix for this in the nginx & php repo so that it will now fire the php build before the nginx build this allows the config file to be update. 

Please reinstall you app using the latest nginx and php repo:

```
rhc create-app -s test http://cartreflect-claytondev.rhcloud.com/github/boekkooi/openshift-cartridge-nginx
rhc cartridge add -a test http://cartreflect-claytondev.rhcloud.com/github/boekkooi/openshift-cartridge-php
```

**Comment by weplan9** [comment]
I will test and report.

Another small issue, I don't even know if it's an issue or just a limitation of the way openshift works.

To continue development, updating php files without getting the gear restarted we need to create a file in `.openshift/markers/hot_deploy`

If we have this file uploaded to the repo and try to scale up it throws an error.
To fix this i had to remove `.openshift/markers/hot_deploy` from my repo.

Do you think if this is an issue or just a openshift limitation?

Thanks again for your amazing support.

**Comment by boekkooi** [comment]
Hey so hot deploy is currently not supported so please create a new issue or a PR 😃
