### ISSUE TITLE
Openshift deployment failure

### ISSUE THREAD

**Issue by yarunkumar** [boekkooi/openshift-cartridge-nginx#6]
I am trying to deploy exisitng ruby on rails app(sqlite3) to Openshift followin

http://www.arubystory.com/2013/12/tutorial-todo-rails-openshift.html

How ever after getting to the point of deployment, I am getting the below error,
remote:  = 1.8.7 : gem install rdoc-data; rdoc-data --install
remote:  = 1.9.1 : gem install rdoc-data; rdoc-data --install
remote: >= 1.9.2 : nothing to do! Yay!
remote: Preparing build for deployment
remote: Deployment id is bf35ba79
remote: Activating deployment
remote: rake aborted!
remote: Gem::LoadError: Specified 'sqlite3' for database adapter, but the gem is not loaded. Add `gem 'sqlite3'` to your Gemfile (and ensure its version is at the minimum required by ActiveRecord).
remote: /var/lib/openshift/5677033589f5cfe207000097/app-root/runtime/repo/vendor/bundle/ruby/gems/activerecord-4.1.8/lib/active_record/connection_adapters/connection_specification.rb:190:in `rescue in spec'
remote: /var/lib/openshift/5677033589f5cfe207000097/app-root/runtime/repo/vendor/bundle/ruby/gems/activerecord-4.1.8/lib/active_record/connection_adapters/connection_specification.rb:187:in`spec'
remote: /var/lib/openshift/5677033589f5cfe207000097/app-root/runtime/repo/vendor/bundle/ruby/gems/activerecord-4.1.8/lib/active_record/connection_handling.rb:50:in `establish_connection'
remote: /var/lib/openshift/5677033589f5cfe207000097/app-root/runtime/repo/vendor/bundle/ruby/gems/activerecord-4.1.8/lib/active_record/railtie.rb:129:in`block (2 levels) in class:Railtie'
remote: /var/lib/openshift/5677033589f5cfe207000097/app-root/runtime/repo/vendor/bundle/ruby/gems/activesupport-4.1.8/lib/active_support/lazy_load_hooks.rb:38:in `instance_eval'
remote: /var/lib/openshift/5677033589f5cfe207000097/app-root/runtime/repo/vendor/bundle/ruby/gems/activesupport-4.1.8/lib/active_support/lazy_load_hooks.rb:38:in`execute_hook'
remote: /var/lib/openshift/5677033589f5cfe207000097/app-root/runtime/repo/vendor/bundle/ruby/gems/activesupport-4.1.8/lib/active_support/lazy_load_hooks.rb:28:in `block in on_load'
remote: /var/lib/openshift/5677033589f5cfe207000097/app-root/runtime/repo/vendor/bundle/ruby/gems/activesupport-4.1.8/lib/active_support/lazy_load_hooks.rb:27:in`each'
remote: /var/lib/openshift/5677033589f5cfe207000097/app-root/runtime/repo/vendor/bundle/ruby/gems/activesupport-4.1.8/lib/active_support/lazy_load_hooks.rb:27:in `on_load'
remote: /var/lib/openshift/5677033589f5cfe207000097/app-root/runtime/repo/vendor/bundle/ruby/gems/activerecord-4.1.8/lib/active_record/railtie.rb:118:in`block in class:Railtie'
remote: /var/lib/openshift/5677033589f5cfe207000097/app-root/runtime/repo/vendor/bundle/ruby/gems/railties-4.1.8/lib/rails/initializable.rb:30:in `instance_exec'
remote: /var/lib/openshift/5677033589f5cfe207000097/app-root/runtime/repo/vendor/bundle/ruby/gems/railties-4.1.8/lib/rails/initializable.rb:30:in`run'
remote: /var/lib/openshift/5677033589f5cfe207000097/app-root/runtime/repo/vendor/bundle/ruby/gems/railties-4.1.8/lib/rails/initializable.rb:55:in `block in run_initializers'
remote: /var/lib/openshift/5677033589f5cfe207000097/app-root/runtime/repo/vendor/bundle/ruby/gems/railties-4.1.8/lib/rails/initializable.rb:54:in`run_initializers'
remote: /var/lib/openshift/5677033589f5cfe207000097/app-root/runtime/repo/vendor/bundle/ruby/gems/railties-4.1.8/lib/rails/application.rb:300:in `initialize!'
remote: /var/lib/openshift/5677033589f5cfe207000097/app-root/runtime/repo/config/environment.rb:5:in`<top (required)>'
remote: /var/lib/openshift/5677033589f5cfe207000097/app-root/runtime/repo/vendor/bundle/ruby/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:247:in `require'
remote: /var/lib/openshift/5677033589f5cfe207000097/app-root/runtime/repo/vendor/bundle/ruby/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:247:in`block in require'
remote: /var/lib/openshift/5677033589f5cfe207000097/app-root/runtime/repo/vendor/bundle/ruby/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:232:in `load_dependency'
remote: /var/lib/openshift/5677033589f5cfe207000097/app-root/runtime/repo/vendor/bundle/ruby/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:247:in`require'
remote: /var/lib/openshift/5677033589f5cfe207000097/app-root/runtime/repo/vendor/bundle/ruby/gems/railties-4.1.8/lib/rails/application.rb:276:in `require_environment!'
remote: /var/lib/openshift/5677033589f5cfe207000097/app-root/runtime/repo/vendor/bundle/ruby/gems/railties-4.1.8/lib/rails/application.rb:389:in`block in run_tasks_blocks'
remote: /var/lib/openshift/5677033589f5cfe207000097/app-root/runtime/repo/vendor/bundle/ruby/gems/sprockets-rails-2.3.3/lib/sprockets/rails/task.rb:64:in `block (2 levels) in define'
remote: Tasks: TOP => environment
remote: (See full trace by running task with --trace)
remote: -------------------------
remote: Git Post-Receive Result: failure
remote: Activation status: failure
remote: Activation failed for the following gears:
remote: 5677033589f5cfe207000097 (Error activating gear: CLIENT_ERROR: Failed to execute: 'control deploy' for /var/lib/openshift/5677033589f5cfe207000097/ruby
remote: #IO:0x00000001981380
remote: #IO:0x00000001981308
remote: )
remote: Deployment completed with status: failure
remote: postreceive failed
To ssh://5677033589f5cfe207000097@efss-arunresearch.rhcloud.com/~/git/efss.git/
   dde82df..a01404c  master -> master

I validated my gem file it has sqlite3 mentioned and application in openshift still shows as deploying status. i try to stop the server and restart but it shows service unavailable.
 even if I ignore and go to ssh in to app it shows the same error.

can someone please help

**Comment by boekkooi** [comment]
Hi @yarunkumar 
I'm sorry but I have no experience deploying ruby on openshift and it looks like the problem is there and no in the cartridge (but I maybe wrong). 

After a quick google search you may take a look at these stackoverflow questions:
- http://stackoverflow.com/questions/24336809/gemloaderror-specified-sqlite3-for-database-adapter-but-the-gem-is-not-loa
- http://stackoverflow.com/questions/20563185/loaderror-specified-sqlite3-for-database-adapter
- http://stackoverflow.com/questions/17781422/rails-4-sqlite3-gemloaderror

If this is a actual problem with the cartridge please reopen the issue so I can help you find the problem and fix it.
