### ISSUE TITLE
Issues with Adding SSL

### ISSUE THREAD

**Issue by EnumC** [boekkooi/openshift-cartridge-nginx#8]
Hello, I am trying to add support for SSL for the past 3 hours. When I add a new server {} to listen on port 80, and redirects to 443, the cartridge won't start up. If I bind the server to any ports other than 8080, it won't start up. Is there any way to listen on a different port? I normally just do the same thing, and it will work. But this doesn't. I am assuming something went wrong with the way it handles ports. Thanks.

Current config:

server {
    listen      80;
    server_name mydomain.com www.mydomain.com;
    return      301         https://www.mydomain.com$request_uri;
}

server {
    listen              443 ssl;
    root    /var/lib/openshift/56a181760fefece89fwcsa25/app-root/runtime/repo//public;
    location / {
        index  index.html index.htm;
    }
}

**Comment by boekkooi** [comment]
Hi @Eric1084 

So the reason for this is that you can't because the openshift architecture is a little different then just a VM. To add a ssl certificate see https://developers.openshift.com/en/managing-domains-ssl.html#using-a-custom-ssl-certificate

If you really do want to open a port for ssl it is possible but you will need to edit the endpoints in `https://github.com/boekkooi/openshift-cartridge-nginx/blob/master/metadata/manifest.yml`

Good luck!

**Comment by rscorer** [comment]
If you're lazy like me, you can create a free CloudFlare account and they will front an https for you. They generate a browser friendly SSL certificate, and then even allow caching to your app. I find it very useful, also they take over your DNS for your site - but they are incredibly responsive when you change an entry.
Been very happy with CloudFlare.
Another hint is to use LetsEncryot to get a free SSL cert for your site!

**Comment by EnumC** [comment]
@boekkooi , Thanks for your prompt response. I did add the ssl certificate in openshift within the web counsole. But what I am trying to accomplish, is to forward regular(Non-HTTPS) traffic to the https-enabled site. I tried rewrite, but that just caused a redirect loop. And I tried the port 80 to https approach, but that didn't work either, as the cartridge won't start up anymore.  Is there a way of doing that? Also, I am quite curious. How did you manage to host the server on port 8080, and retain the ability to connect with default port settings(80)? Thank you.

-Eric

**Comment by boekkooi** [comment]
Hi @Eric1084 

I'm not sure what you are trying to do but maybe it would help you to read [OpenShift Origin Cartridge Developer’s Guide](https://docs.openshift.org/origin-m4/oo_cartridge_developers_guide.html#exposing-services-tcp-endpoints) also [New OpenShift Cartridge Format – Part 1](https://blog.openshift.com/new-openshift-cartridge-format-part-1/) this for example states "Port 80 is changed to port 8080 for reasons described above, a regular unix user can’t bind to port 80". 

I hope this helps if you need more help please provide some logs of and config files so I can give you some tips.

**Comment by EnumC** [comment]
Alrighty. I'll just use javascript forwarding for now. That seems to be the simplest way of doing it. Thanks for your help.
