### ISSUE TITLE
PCRE_VERSION='8.36' is no longer available

### ISSUE THREAD

**Issue by hmarrao** [boekkooi/openshift-cartridge-nginx#9]
Changed and tested with 8.38 in the build and it worked!

**Comment by boekkooi** [comment]
Hi @hmarrao Could you please create a PR changing the version? Thank you!

**Comment by hmarrao** [comment]
Hi @boekkooi compiling it now.
but only should pull request the new version 1.9.12 our should I pull request all the builds¿?
saying this because the app is compiling all available versions with the pcre-3.38

**Comment by boekkooi** [comment]
Your PR was great @hmarrao thanks!
